### ISSUE TITLE
TG Soil - option to extend soilproperty codelists wider then chemical, physical, biological

### ISSUE THREAD

**Issue by pvgenuchten** [INSPIRE-MIF/technical-guidelines#101]
# Change proposal description
As various players in the soil domain we endorse to allow to extend the codelists of soil properties wider than the current constraint from the TG, to be narrower then chemical, physical and biological. So we can describe also descriptive properties such as color, stoniness, etc.

## Addressed TG
[D2.8.III.3 Data Specification on Soil – Technical Guidelines
](https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_SO_v3.0.pdf)

## Location

[paragraph 5.3.2.3.8.](https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.2/data/so/dataspecification_so.adoc#53238-profileelementparameternamevalue)

## Issue faced

Currently paragraph [53238](https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.2/data/so/dataspecification_so.adoc#53238-profileelementparameternamevalue) lists 3 categories (chemical, physical, biological) of profile element parameters with an option to extend these categories `narrower` only.

## Proposed solution

On a recent [masterclass on INSPIRE practices in the Soil domain](https://ejpsoil.github.io/soildata-assimilation-guidance/masterclass/) for soil institutes it was suggested to add a 4th category; 'descriptive parameters', which would be able to capture observations from the field, not from a lab. Such as mottle %, mottle size, color, stoniness etc. Another option here would be to allow the codelist to be extended at the rootlevel (relieve the requirement to be narrower then the 3 categories).

### Pull request

# Additional information

## Impact on INSPIRE code lists

The population of this section of the registry is currently quite limited, no impact is expected.

### Linked issue

https://github.com/INSPIRE-MIF/helpdesk/discussions/143

## Change proposer

- Paul van Genuchten, ISRIC - World Soil Information, EJP Soil
- Fenny van Egmond, Wageningen Environmental Research, EJP Soil

**Comment by KathiSchleidt** [comment]
@fabiovinci : I fear you're misinterpreting the IRs here. 

- The observedProperty of the Observation provides WHAT was measured. The codelists ProfileElementParameterNameValue, SoilDerivedObjectParameterNameValue, SoilProfileParameterNameValue, SoilSiteParameterNameValue provide these. (Using "ParameterName" in these observedProperty codelists can lead to confusion)
- The parameter of the Observation can be used to provide **additional** information relevant to this Observation, usually calibration information. I've added the full description from the O&M standard below.

When an Observation is used to provide data, there must be a link to an observedProperty. The parameter CAN NOT be used for this purpose.

@pvgenuchten : on your original issue of extending the initial 3 root elements (chemicalParameter, biologicalParameter, physicalParameter) by the additional 4th category; 'descriptive parameters', I'm trying to understand the rational behind this. To my view, your examples (mottle %, mottle size, color, stoniness etc. ) all look like physicalParameters. If the only reason for differentiation is to split between observations from the field vs. from a lab, I'd advise against this split (pretty sure there are some observedProperty that can be determined both in the field and in the lab). 

Can you describe the difference between physical parameter and described parameter?


**Parameter Definition from O&M (ISO 19156):**
If present, the attributes parameter:NamedValue shall describe an arbitrary event-specific parameter. This might be an environmental parameter, an instrument setting or input, or an event-specific sampling parameter that is not tightly bound to either the feature-of-interest (6.2.2.7) or to the observation procedure (6.2.2.10). To avoid ambiguity, there shall be no more than one parameter with the same name. 

NOTE	Parameters that are tightly bound to the procedure may be recorded as part of the procedure description. 

In some contexts the Observation::procedure (6.2.2.10) is a generic or standard procedure, rather than an event-specific process. In this context, parameters bound to the observation act, such as instrument settings, calibrations or inputs, local position, detection limits, asset identifer, operator, may augment the description of a standard procedure. 

EXAMPLE	A time sequence of observations of water quality in a well may be made at variable depths within the well. While these may be associated with specimens taken from the well at this depth as the features-of-interest, a more common approach is to identify the well itself as the feature-of-interest, and add a “samplingDepth” parameter to the observation (Figure 3). The sampling depth is of secondary interest compared to the temporal variation of water quality at the site.

**Comment by pvgenuchten** [comment]
I’ll check with colleagues, my impression from the meeting was that it was understood physical and chemical refer to measured parameters on samples in a lab, and descriptive parameters would refer to visual observations by experts in the field, such as color, stoniness, vegetation, slope shape. Indeed one can argue that some of these are indeed physical parameters…

**Comment by fabiovinci** [comment]
Sub-group meeting on 17.04.2023:
considering that an agreement on the opportunity to extend the codelist at the first level seems not yet been reached, the sub-group decided to postpone the discussion leaving the issue open for further input.

**Comment by ldesousa** [comment]
Just to note that most of the properties in the [original list](https://github.com/INSPIRE-MIF/technical-guidelines/issues/101#issuecomment-1508676046) refer to the GloSIS classes `GL_Layer` and `GL_Horizon`, their equivalent code-list in INSPIRE is `ProfileElementParameterNameValue`.

**Comment by KathiSchleidt** [comment]
Bringing this issue back on topic, whether we require an additional top level categorization for ObservableProperties within the context of INSPIRE Soil:

- All lists provided have worked with the existing three top level categories of "biological", "chemical", "physical"
- Subsequent (offline, apologies) discussions have shown that the core issue has to do with analysis methods, that are covered in the O&M Procedure

Based on these insights, the existing categories for ObservableProperties seem sufficient. However, if/when we set up standardized Procedures, we may want to classify them as follows:
- Pedo-genetic description
- Field estimate
- Laboratory analysis

In addition, a link between ObservableProperty and Procedure would be valuable.

As to adding the lists of ObservableProperties provided in the posts above to the existing INSPIRE ObservableProperty, for this purpose, we'd need separate issues under the [registry repo](https://github.com/INSPIRE-MIF/helpdesk-registry) for this. In addition, such additions should be proposed by a relevant community, e.g. EJP-Soil. As a reminder, pertains to the following 4 codelists:

- [Profile Element Parameter Name](https://inspire.ec.europa.eu/codelist/ProfileElementParameterNameValue): Layers and Horizons
- [Soil Derived Object Parameter Name](https://inspire.ec.europa.eu/codelist/SoilDerivedObjectParameterNameValue): Soil Bodies and Coverages
- [Soil Profile Parameter Name](https://inspire.ec.europa.eu/codelist/SoilProfileParameterNameValue): Soil Profiles
- [Soil Site Parameter Name](https://inspire.ec.europa.eu/codelist/SoilSiteParameterNameValue): Soil Sites

To my view, this issue can be closed as resolved

**Comment by pvgenuchten** [comment]
Agree Kathy, thank you all for the wonderful discussion.

@fabiovinci can I close this (as not planned)?

**Comment by fabiovinci** [comment]
Dear @pvgenuchten,
yes, we can close the issue as it does not require changes to either TG or IR.

Thank you all for your contribution.
