### ISSUE TITLE
View Service - requirement for layer name for harmonised datasets

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#12]
This is a placeholder for the issue that was mentioned in https://github.com/INSPIRE-MIF/technical-guidelines/issues/2#issuecomment-920948621.

**Comment by doemming** [comment]
# Change proposal description

This proposals complements https://github.com/INSPIRE-MIF/technical-guidelines/issues/2 to propose a requirement to the TG for view services for layer names for harmonised datasets.

## Addressed TG

[Guidance for the implementation of INSPIRE View Services](https://inspire.ec.europa.eu/file/1556/download?token=2IJ7xEJG) , Version 3.11

## Location

p. 38, 4.2.3.3.4.6 NAME



## Issue faced

An INSPIRE compliant view service may provide layers of harmonised and non-harmonised data sets. 
The issue https://github.com/INSPIRE-MIF/technical-guidelines/issues/2 updates the TG to allow providing non-hamonised layers for "as-is" datasets.
This change proposal addresses the requirements of Article 14 [INS DS] without requiring that only harmonized layers be provided in a view service.

## Proposed solution

**Additional Requirement**:
In case the view service provides harmonised layers according to [INS DS] the names of these layers shall comply with the harmonised layer names defined in Article 14 of [INS DS].

**Note**: 
 _A view service may contain harmonized and/or non-harmonized layers._



### Pull request

Not available as the TG is not yet available in the repository.

# Additional information

## Kind of issue

technical

## Relevant legislation


[IR interoperability spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId16)

## Impact on IR

None.

## Impact on INSPIRE validator

The ETS regarding INSPIRE view services needs to be updated accordingly. One solution is already available in the staging instance of the validator.
The test related to the IR-ISDSS requirement could be added as a separated conformance class to the ETS for view services (similar to the way that this is being done for the metadata requirements for interoperability based on requirements in the IR-ISDSS).

### Linked issue

[INSPIRE-MIF/helpdesk-validator#39](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39)

## Impact on INSPIRE XML schemas

None

## Impact on INSPIRE code lists

None

## Change proposer

German MIG-T Members

## References


- [INSPIRE-MIF/helpdesk-validator#39](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39)
- https://github.com/INSPIRE-MIF/technical-guidelines/issues/2

**Comment by heidivanparys** [comment]
> The test related to the IR-ISDSS requirement could be added as a separated conformance class to the ETS for view services (similar to the way that this is being done for the metadata requirements for interoperability based on requirements in the IR-ISDSS).

For the conformance classes regarding metadata, see https://github.com/inspire-eu-validation/metadata/tree/2.0#conformance-classes-relations-and-dependencies:

<img src="https://github.com/inspire-eu-validation/metadata/blob/845915ce796af3bfc814a1f9b2e13fbf518a465b/hierarchydiagram.jpg?raw=true" width="800" alt="Conformance classes metadata">

Something similar could be done for view services (for discussion in the subgroup):

<img src="https://user-images.githubusercontent.com/11427611/146073148-aeafdd24-a340-47c9-a6f6-fa6d87b34aea.png" width="600" alt="Conformance classes view service">

For discussion:

- Where in the TG should this requirement be added? Adding it right after requirement 39 could be confusing, perhaps a new section 4.3.4 should be added to accommodate this requirement? Other proposals?
- To avoid any confusion, it would be good to formulate a test already (see the current test for requirement 39 at https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/at39-getcapabilities-layer-name.md). How to check for “In case the view service provides harmonised layers according to [INS DS]” should be described very clear. And is that part of the test itself, or is it part of the prerequisites to actually run this test suite? Or a test by itself? A WMS service serving non-harmonised data should not be able to pass this conformance class.

**Comment by heidivanparys** [comment]
Meeting 15-12-2021: the second conformance must take into account that some of the layers still may be as-is data. This is a common use case.

How do we know what layers are harmonised?

We should elaborate on this proposal. More examples? Proposal for the test?

**Comment by hogredan** [comment]
> Where in the TG should this requirement be added? Adding it right after requirement 39 could be confusing, perhaps a new section 4.3.4 should be added to accommodate this requirement? Other proposals?

@heidivanparys why do you think that it could be confusing adding the new requirement right after requirement 39? Basically, I would prefer the requirement to be added somewhere in section _4.2.3 Get View Service Metadata operation_ . I don't think a new section 4.3.4 below _4.3 Language Requirements_ would be appropriate.

**Comment by hogredan** [comment]
Requirements 33, 42 and 85 of the TG reference the interoperability regulation as well. We should check to what extent these also need to be updated in order to keep the TG consistent.

![image](https://user-images.githubusercontent.com/18457212/146917912-d09f6a26-78da-4a4e-89c3-7e9348a9313b.png)
![image](https://user-images.githubusercontent.com/18457212/146918092-b8fa6b74-e927-49ff-b4bb-123610a2b3ba.png)
![image](https://user-images.githubusercontent.com/18457212/146918201-5e328d0b-512e-4a21-9baf-aad074e9e894.png)

**Comment by hogredan** [comment]
Proposal for adding a new requirement on harmonized layer names to the TG (based on the proposed solution of issue #2):

```4.2.3.3.4.6 NAME
The name of the layer.
  
Implementation Requirement 39 Name shall be mapped with the <wms:Name> element.

Implementation Requirement 93 In case a layer is a harmonised layer according to [INS DS] 
the layer name shall comply with the harmonised layer name defined in Article 14 of [INS DS].

NOTE A view service may contain one or more harmonised and/or one or more non-harmonised layers.
``` 

The test case for req. 39 in the conformance class 'View Service WMS' (https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/at39-getcapabilities-layer-name.md) should be updated as followed (remove bullet point 'Check that the value of the Layer Name element matches one of the harmonised layer names given in TG VS or its amendments.'):

```
  For each named Layer element:
   - Check that exactly one Layer Name element is provided and it has a non-empty value.
   - Check that Layer Name is unique.
```

The new requirement 93 would only be testable manually, as it seems impossible to distinguish harmonised layers from non-harmonised layers (in case there is a view service which provides both, harmonised and non-harmonised layers).

Therefore, we would propose to create a new conformance class 'View Service WMS - interoperability requirements'. This new conformance class would include a new manual test case where the user gets information about the number of harmonised layers included in the service and their names. Then, the user is able to check manually if all harmonised layer names are correct.

Other requirements that are referenced to the interoperability regulation and might be added to the new conformance class:

  - Req. 33: Layer Title (https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/at33-getcapabilities-layer-title.md) --> Actually, the test case doesn't include any check regarding harmonised layer titles. No move to the new conformance class needed.
 
   - Req. 42: Layer Default Style (https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/at42-getcapabilities-layer-default-style.md)

For WMTS only one requirement is referenced to the interoperability regulation:

   - Req. 85: Layer Title (https://github.com/inspire-eu-validation/view-service/blob/master/wmts-1.0.0/at85-getcapabilities-layer-title.md) --> The ATS points out that "the validation of the correctness of the translated title is not done due to it's complexity and the controversy over the usefulness of the harmonised layer titles." Thus, for WMTS no changes are needed.

In the TG we would propose to change the Req. 33, 42 and 85 as followed to clarify the different requirements for harmonised and non-harmonised layers:

```
Implementation Requirement 33 The Ressource title is mapped with <wms:Title>. 
For each harmonised layer according to [INS DS] the title is mapped to the harmonised 
title defined by [INS DS] and shall be subject of multilingualism (translations shall appear 
in each mono-lingual capabilites localized documents). 
```
```
Implementation Requirement 42 For each harmonised layer according to [INS DS] an 
<inspire_common:DEFAULT> style shall be as defined in the "Portrayal" section of the 
[INS DS, Article 14].
```
```
Implementation Requirement 85 The Resource title of the layer, used for human 
communication, for example presentation of the layer in a menu. It is mapped with 
<ows:Title>. For each harmonised layer according to [INS DS] the title is mapped to 
the harmonised title defined by [INS DS] and shall be subject of multilingualism 
(translations shall appear in each mono-lingual capabilites localized documents). 
```

**Comment by sMorrone** [comment]
**Summing up:**

Current  **_Implementation Requirement 39_**
![image](https://user-images.githubusercontent.com/13329248/159948208-450835d6-b629-4936-b1b5-7d734b92a620.png)
 is modified as follows (considering also endorsed change proposal #2):
**_Implementation Requirement 39_** Name shall be mapped with the  `<wms:Name>` element.

**_Implementation Requirement 39 bis_** In case a layer is a harmonised layer according to [INS DS], the layer name shall comply with the harmonised layer name defined in Article 14 of [INS DS].

**_NOTE:_** A view service may contain one or more harmonised and/or one or more non-harmonised layers.

Current  **_Implementation Requirement 33_**
![image](https://user-images.githubusercontent.com/13329248/159948682-b9a25661-82ed-414c-ac8c-4be892ab301e.png)
is modified as follows:
**Implementation Requirement 33:** it is mapped with `<wms:Title>`. For each harmonised layer according to [INS DS] the title is mapped to the harmonised title defined by [INS DS] and shall be subject to multilingualism (translations shall appear in each mono-lingual capabilities localized documents). 

Current  **_Implementation Requirement 42_**
![image](https://user-images.githubusercontent.com/13329248/159948794-6f28fe28-2d5f-4693-98c0-3ce6b0e14aba.png)
is modified as follows:
**_Implementation Requirement 42_** For each harmonised layer according to [INS DS] an `<inspire_common:DEFAULT>` style shall be as defined in the "Portrayal" section of the [INS DS, Article 14].

Current  _**Implementation Requirement 85**_ 
![image](https://user-images.githubusercontent.com/13329248/159952418-84af5232-f47f-409c-b03b-b1af8d96c9d2.png)
is modified as follows:
**_Implementation Requirement 85_** The Resource title of the layer, used for human communication, for example presentation of the layer in a menu. It is mapped with `<ows:Title>`. For each harmonised layer according to [INS DS] the title is mapped to the harmonised title defined by [INS DS] and shall be subject of multilingualism (translations shall appear in each mono-lingual capabilites localized documents).

**Comment by sMorrone** [comment]
Subgroup meeting on 24.03.2022:
the Subgroup approved this change proposal.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
