### ISSUE TITLE
CP – Technical Guidelines: UML graph

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/technical-guidelines#50]
Dear

I  hope you are all right. 

As I wrote [here ](https://github.com/INSPIRE-MIF/helpdesk/issues/108)I noticed that administrativeUnit relation is missing from UML graphes of both CadastralParcel featurey type and BasicPropertyUnit thuough they are specified by Regulation 1089/2010 and by textual descriptions of CP - Technical Guidelines. 

In the same kind of idea I noticed that the GeographicalName class that should be instancied in CadastralZoning is not shown on the UML grpah.

Could I suggest to add both of them in all the concerned classes?

Moreover I noticed the same problem [here](https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/) but I don't know if these data models are meant to be updated or not.

Regards,

**Comment by fabiovinci** [comment]
Dear @bfrichet3,

the relations you mentioned are available in the folder "External relations"

![image](https://user-images.githubusercontent.com/22212406/177346159-4be416eb-5b3d-4b07-a149-5e4a0c33a285.png)

**Comment by bfrichet3** [comment]
dear @fabiovinci 

I know but I noticed in AU theme that external classes are sometimes directly specified in the main UML

![image](https://user-images.githubusercontent.com/80756452/177346886-a11b8caa-dec4-4037-bd3d-765fb1fad548.png)


Maybe this comes from that name attribute is not a relation in the meaning of 1089/2010

**Comment by fabiovinci** [comment]
Dear all,

to align the UML and TG of the CP data theme with the other data themes, we could move the reference to the external data type in the main UML view (see the picture below), and substitute Figure 2 in the TG.

![CP_UML_view_proposal](https://user-images.githubusercontent.com/22212406/188660347-97fbc25c-0ef3-4e87-8458-4602017862b9.png)

In addition, we could move the UML view that shows the associations with other data themes from the "External relations" folder to the main one, as shown in the picture below.

![image](https://user-images.githubusercontent.com/22212406/188662417-b321bdeb-2fc0-444e-a741-159e9b07402a.png)

The same view could be added to the TG, since it is not present at the moment, as Figure 4 or by replacing Figure 3, which seems redundant and is not mentioned in the text.

**Comment by sMorrone** [comment]
Subgroup meeting on 13.09.2022:
subgroup approves. Since the proposed change is editorial, it will be implemented directly by the JRC

**Comment by bfrichet3** [comment]
@sMorrone , thank you for your answer. Do you when these changes are to be implemented?

**Comment by fabiovinci** [comment]
The approved changes were applied to the UML model and will be released in the 2024.1 release.
The related changes in the TG will be applied as soon as the TG is available in asciidoc format.
